//GLOBAL VARIABLES
int SelectedLine = 1;
		int RosettaFlash = 1;
		int carr[4] = {1, 2, 3, 4};
		int sarr[4] = {1, 2, 3, 4};
		int tarr[4] = {1, 2, 3, 4};
		int done = 0;
		int firstcard = 1;
		Image* ptemp;
		int cardnum = 0;
		int cardxlocation=11;
	int cardylocation=10;
	char cardimage1[20];
	char cardimage2[20];
	char cardimage3[20];
	char cardimage4[20];
	int cardfirst;
	int cardlast;
int cardselect1 = PSP_CTRL_UP;
int cardselect2 = PSP_CTRL_DOWN;
int cardselect3 = PSP_CTRL_TRIANGLE;
int cardselect4 = PSP_CTRL_CROSS;
int cardreplay = PSP_CTRL_SQUARE;
int cardslowreplay	= PSP_CTRL_CIRCLE;
		char correctscoreprint[3];
		char incorrectscoreprint[3];
		char unitlesson[30];
		char unitlessonpace[2];
		int unitlessonpaceX;
		int CorrectScorePrintX;
		int inCorrectScorePrintX;
		char correctSoundTxt[10];
		char incorrectSoundTxt[10];
		char correctSound[30];
		char incorrectSound[30];
		int correctSelect=1;
		int incorrectSelect=1;
		int keepgoing = 1;
		int correctscore=0;
		int incorrectscore=0;
		int scorestatus=3;
		int scorechecked=0;
		char cardtext[100];
		int soundcall = 0;
		int controlSchemeStatus = 1;
		int TutorialStatus = 1;
		int tutorialcheck;
		char tutorialcheckTxt[1];
	int roseUnit = 1;
	int roseLesson = 1;
	char roseUnitTxt[2];
	char roseLessonTxt[2];
	
	char langSoundMp3[5];
	char langSoundDir[5];
	char langImagePNG[5];
	char langImageDir[5];
		char langName1[30];
int ArabicI = 0;
int ArabicII = 0;
int ChineseI = 0;
int ChineseII = 0;
int DanskI = 0;
int NederlandsI = 0;
int NederlandsII = 0;
int EnglishUKI = 0;
int EnglishUKII = 0;
int EnglishUSI = 0;
int EnglishUSII = 0;
int FrancaisI = 0;
int FrancaisII = 0;
int DeutschI = 0;
int DeutschII = 0;
int GreekI = 0;
int GreekII = 0;
int HebrewI = 0;
int HindiI = 0;
int IndonesianI = 0;
int ItalianoI = 0;
int ItalianoII = 0;
int JapaneseI = 0;
int JapaneseII = 0;
int KoreanI = 0;
int LatinI = 0;
int PortugeusI = 0;
int PortugeusII = 0;
int RussianI = 0;
int RussianII = 0;
int EspagnolI = 0;
int EspagnolII = 0;
int SpanishSpainI = 0;
int SpanishSpainII = 0;
int KiswahiliI = 0;
int SvenskaI = 0;
int ThaiI = 0;
int TurkishI = 0;
int VietnameseI = 0;
int CymraegI = 0;
int DemoSet = 0;
int selectmenustatus = 1;
int soundmenustatus = 1;
int scoreCardStatus = 1;
		int langUnit;
		int langLesson;
		int lessonlength = 40;
		char lessonDescTxt[100];	
FILE * pFile;
char c, c2, readText[200] = " "; 
int n = 0, x, xz, x2, size, readTextPlace;
Image* SelectMenuPNG;

Image* sprite;
Image* splash;
Image* logo;
Image* fontWestern;

int sprite_march = 1;
int sprite_position = 170;
int Char = 1;
int TextX = 4;
int TextY = 5;

int frameX = 99;
int frameY = 0;

int counta = 0;
typedef short bool;
bool FileExist;
int detectedUnits[20][40];
int unitCount=1;
int lessonCount=1;
char FolderName[40];

int availableLessons = 0;
int availableUnits = 0;
int availableLessonsByUnit[40];
int availableUnitsByUnit[40];
int loadingstatus = 0;
int placedunit = 0;
int placedlesson = 0;
int UnitExists = 0;
char flashsound[100];
char imgType[5];
char audType[5];
int audioType = 2;
int xix;

int AllLoaded = 0;

void loadtheflash(int cardfirst, int cardlast);
